### ISSUE TITLE
ClrAttributeResolver.EnsureFrameworkAssembliesLoaded can ICE the compiler: BadImageFormatException from Assembly.GetName() over loaded assemblies

### ISSUE THREAD

**Issue by antonsynd** [antonsynd/sharpy#1840]
Observed while verifying branch `v5/clr-member-types` (#1705). Not caused by that change: the same
tests pass in isolation, in every subset, and on a repeat of the same filter.

## Symptom

Two tests in `Sharpy.Compiler.Tests` fail nondeterministically with the same fault:

```
Sharpy.Compiler.Tests.Discovery.AttributeAbsenceVerdictScopeTests.AnAbsenceVerdict_DoesNotSurviveIntoTheNextCompilation
  System.BadImageFormatException : Index not found. (0x80131124)
     at System.Reflection.RuntimeAssembly.GetLocale(...)
     at System.Reflection.RuntimeAssembly.GetName(Boolean copiedName)
     at Sharpy.Compiler.Discovery.ClrAttributeResolver.EnsureFrameworkAssembliesLoaded(String) ClrAttributeResolver.cs:415
     at Sharpy.Compiler.Discovery.ClrAttributeResolver.ResolvesToClrType(...) ClrAttributeResolver.cs:239

FileBasedIntegrationTests decorators/bracket_attr_import_redundant_always_in_scope_1429
  Compilation failed: internal compiler error (BadImageFormatException) in DecoratorValidator:
  Index not found. (0x80131124)
```

The second one is user-facing: a reflection scan over the assemblies loaded in the process turns
into an SPY internal-compiler-error for a program that has nothing wrong with it.

## Evidence that it is order/parallelism dependent, not a code defect in the branch

Measured at 87025241b on branch `v5/clr-member-types`, filter
`Discovery|UnsubstitutedTypeParameterGuardTests|ClrInterop|FileBasedIntegrationTests|ClrMemberFidelity|ClrNullability|ClrMemberTypeWarmCold`:

| run | result |
|---|---|
| first | 3766 passed / 5 failed (3 of them this fault) |
| same filter, no source change | 3770 passed / 1 failed (this fault, decorators fixture) |
| same filter again | 3771 passed / 0 failed |
| `DisplayName~bracket_attr_import_redundant` alone | 3 passed |
| `Discovery` + that fixture (388 tests) | 388 passed |
| `FileBasedIntegrationTests` + warm/cold (3306 tests) | 3306 passed |

Logs: `sharpy.worktrees/verify-logs/fix-clrmembers-{7,final-compiler,final2,14,16,17}.log`.

## Likely cause and fix

`EnsureFrameworkAssembliesLoaded` enumerates the process's loaded assemblies and reads
`assembly.GetName()`. Any assembly in the test host whose metadata cannot be read at that moment —
a transient assembly a test emitted and whose file has since been replaced or deleted (see #1834 for
one such producer) — makes `GetName()` throw, and the exception escapes into the validator.

Fix: wrap the per-assembly read in a try/catch and skip assemblies that cannot describe themselves
(`BadImageFormatException`, `FileNotFoundException`, `ReflectionTypeLoadException`). A compiler's
attribute resolution should not depend on every other assembly in its process being readable.

**Comment by antonsynd** [comment]
Fixed on dev/mainline @ 41dd19de7 (pushed 2026-09-11) by: 9717e239e (ClrAttributeResolver.EnsureFrameworkAssembliesLoaded: one unreadable assembly no longer ICEs the compiler). Closed from the /verify-implementation remediation round of plans P7b/P7c/P9/P3/P4.
